site_name: Wiki Tinder
pages:
     - Home: index.md
     - Pré-Rastreabilidade:
         - 'About': 'pre-rastreabilidade/pre-rastreabilidade.md'
         - 'Rich Pictures': 'pre-rastreabilidade/richPicture.md'
         - 'Argumentações': 'pre-rastreabilidade/argumentacoes.md'
         - 'Referências': 'pre-rastreabilidade/referencias.md'
     - Pós-Rastreabilidade:
         - 'About': 'pos-rastreabilidade/pos-rastreabilidade.md'
         - 'Referências': 'pos-rastreabilidade/referencias.md'
         - '01': 'pos-rastreabilidade/cenarios/cenario01.md'
         - '02': 'pos-rastreabilidade/cenarios/cenario02.md'
         - '03': 'pos-rastreabilidade/cenarios/cenario03.md'
         - '04': 'pos-rastreabilidade/cenarios/cenario04.md'
         - '05': 'pos-rastreabilidade/cenarios/cenario05.md'
         - '06': 'pos-rastreabilidade/cenarios/cenario06.md'
         - '07': 'pos-rastreabilidade/cenarios/cenario07.md'
         - '08': 'pos-rastreabilidade/cenarios/cenario08.md'
         - '09': 'pos-rastreabilidade/cenarios/cenario09.md'
         - '10': 'pos-rastreabilidade/cenarios/cenario10.md'
         - '11': 'pos-rastreabilidade/cenarios/cenario11.md'
         - '12': 'pos-rastreabilidade/cenarios/cenario12.md'
         - '13': 'pos-rastreabilidade/cenarios/cenario13.md'
         - '14': 'pos-rastreabilidade/cenarios/cenario14.md'
         - '15': 'pos-rastreabilidade/cenarios/cenario15.md'
         - '16': 'pos-rastreabilidade/cenarios/cenario16.md'
         - '17': 'pos-rastreabilidade/cenarios/cenario17.md'
         - '18': 'pos-rastreabilidade/cenarios/cenario18.md'
         - '19': 'pos-rastreabilidade/cenarios/cenario19.md'
         - '20': 'pos-rastreabilidade/cenarios/cenario20.md'
         - '21': 'pos-rastreabilidade/cenarios/cenario21.md'
         - '22': 'pos-rastreabilidade/cenarios/cenario22.md'
         - '23': 'pos-rastreabilidade/cenarios/cenario23.md'
         - '24': 'pos-rastreabilidade/cenarios/cenario24.md'
         - '25': 'pos-rastreabilidade/cenarios/cenario25.md'
         - '26': 'pos-rastreabilidade/cenarios/cenario26.md'
         - '27': 'pos-rastreabilidade/cenarios/cenario27.md'
         - '28': 'pos-rastreabilidade/cenarios/cenario28.md'
         - '29': 'pos-rastreabilidade/cenarios/cenario29.md'
         - '30': 'pos-rastreabilidade/cenarios/cenario30.md'
         - '31': 'pos-rastreabilidade/cenarios/cenario31.md'
         - '32': 'pos-rastreabilidade/cenarios/cenario32.md'
         - '33': 'pos-rastreabilidade/cenarios/cenario33.md'
     - Elicitação:
         - 'About': 'elicitacao/elicitacao.md'
         - 'Técnicas Elicitação': 'elicitacao/tec_elicitacao.md'
         - 'Observação Participativa': 'elicitacao/observacao_participativa.md'
         - 'Questionário': 'elicitacao/questionario.md'
         - 'Introspecção': 'elicitacao/introspeccao.md'
         - 'Brainstorming': 'elicitacao/brainstorming.md'
         - 'Análise de Protocolo': 'elicitacao/analise_protocolo.md'
         - 'Analise de Discurso': 'elicitacao/analise_discurso.md'
         - 'Storytelling': 'elicitacao/storytelling.md'
         - 'Resultado Técnicas de Elicitação': 'elicitacao/resultado_final_TE.md'
         - 'Técnicas Priorização': 'elicitacao/tec_priorizacao.md'
         - 'MoSCoW': 'elicitacao/moscow.md'
         - 'First Things First': 'elicitacao/first_things_first.md'
         - 'Referências': 'elicitacao/referencias.md'
     - Modelagem:
         - 'About': 'modelagem/modelagem.md'
         - 'Léxicos': 'modelagem/lexicos.md'
         - 'Cenários': 'modelagem/cenarios.md'
         - 'Referências': 'modelagem/referencias.md'
     - Análise:
         - 'About': 'analise/analise.md'
         - 'Referências': 'analise/referencias.md'
     - Extras:
         - 'Linha do Tempo': 'extras/linha-tempo.md'
         - 'Pautas de Reuniões': 'extras/reunioes.md'
         - 'Apresentações': 'extras/apresentacoes.md'
theme:
    name: simplex
extra_css:
  - 'stylesheets/main.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.css'
extra_javascript:
  - 'stylesheets/fancybox-style/jquery.fancybox.js'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.js'
