site_name: Wiki Tinder
pages:
     - Home: index.md
     - Pré-Rastreabilidade:
         - 'About': 'pre-rastreabilidade/pre-rastreabilidade.md'
         - 'Rich Pictures': 'pre-rastreabilidade/richPicture.md'
         - 'Argumentações': 'pre-rastreabilidade/argumentacoes.md'
         - 'Referências': 'pre-rastreabilidade/referencias.md'
     - Pós-Rastreabilidade:
         - 'About': 'pos-rastreabilidade/pos-rastreabilidade.md'
         - 'Referências': 'pos-rastreabilidade/referencias.md'
     - Elicitação:
         - 'About': 'elicitacao/elicitacao.md'
         - 'Técnicas Elicitação': 'elicitacao/tec_elicitacao.md'
         - 'Técnicas Priorização': 'elicitacao/tec_priorizacao.md'
         - 'Intropescção': 'elicitacao/intropesccao.md'
         - 'Observação Participativa': 'elicitacao/obsevacao_participativa.md'
         - 'Questionário': 'elicitacao/questionario.md'
         - 'Storytelling': 'elicitacao/storytelling.md'
         - 'MoSCoW': 'elicitacao/moscow.md'
         - 'First Things First': 'elicitacao/first_things_first.md'
         - 'Referências': 'elicitacao/referencias.md'
     - Modelagem:
         - 'About': 'modelagem/modelagem.md'
         - 'Referências': 'modelagem/referencias.md'
     - Análise:
         - 'About': 'analise/analise.md'
         - 'Referências': 'analise/referencias.md'
     - Extras:
         - 'Linha do Tempo': 'extras/linha-tempo.md'
         - 'Pautas de Reuniões': 'extras/reunioes.md'
         - 'Apresentações': 'extras/apresentacoes.md'
theme:
    name: simplex
extra_css:
  - 'stylesheets/main.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.css'
extra_javascript:
  - 'stylesheets/fancybox-style/jquery.fancybox.js'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.js'
