site_name: Wiki 
pages:
     - Home: index.md
     - Pré-Rastreabilidade:
         - 'About': 'pre-rastreabilidade/pre-rastreabilidade.md'
         - 'Rich Pictures': 'pre-rastreabilidade/richPicture.md'
         - 'Argumentações': 'pre-rastreabilidade/argumentacoes.md'
         - 'Referências': 'pre-rastreabilidade/referencias.md'
     - Pós-Rastreabilidade:
         - 'About': 'pos-rastreabilidade/pos-rastreabilidade.md'
         - 'Referências': 'pos-rastreabilidade/referencias.md'
     - Elicitação:
         - 'About': 'elicitacao/elicitacao.md'
         - 'Técnicas Elicitação': 'elicitacao/tec_elicitacao.md'
         - 'Observação Participativa': 'elicitacao/observacao_participativa.md'
         - 'Questionário': 'elicitacao/questionario.md'
         - 'Introspecção': 'elicitacao/introspeccao.md'
         - 'Brainstorming': 'elicitacao/brainstorming.md'
         - 'Análise de Protocolo': 'elicitacao/analise_protocolo.md'
         - 'Analise de Discurso': 'elicitacao/analise_discurso.md'
         - 'Storytelling': 'elicitacao/storytelling.md'
         - 'Resultado Técnicas de Elicitação': 'elicitacao/resultado_final_TE.md'
         - 'Técnicas Priorização': 'elicitacao/tec_priorizacao.md'
         - 'MoSCoW': 'elicitacao/moscow.md'
         - 'First Things First': 'elicitacao/first_things_first.md'
         - 'Referências': 'elicitacao/referencias.md'
     - Modelagem:
         - 'About': 'modelagem/modelagem.md'
         - 'Léxicos': 'modelagem/lexicos.md'
         - 'Cenários': 'modelagem/cenarios.md'
         - 'Referências': 'modelagem/referencias.md'
     - Análise:
         - 'About': 'analise/analise.md'
         - 'Referências': 'analise/referencias.md'
     - Extras:
         - 'Linha do Tempo': 'extras/linha-tempo.md'
         - 'Pautas de Reuniões': 'extras/reunioes.md'
         - 'Apresentações': 'extras/apresentacoes.md'
     - Pages :
         - 'Cenario 01': 'modelagem/cenarios/cenario01.md'
         - 'Cenario 02': 'modelagem/cenarios/cenario02.md'
         - 'Cenario 03': 'modelagem/cenarios/cenario03.md'
         - 'Cenario 04': 'modelagem/cenarios/cenario04.md'
         - 'Cenario 05': 'modelagem/cenarios/cenario05.md'
         - 'Cenario 06': 'modelagem/cenarios/cenario06.md'
         - 'Cenario 07': 'modelagem/cenarios/cenario07.md'
         - 'Cenario 08': 'modelagem/cenarios/cenario08.md'
         - 'Cenario 09': 'modelagem/cenarios/cenario09.md'
         - 'Cenario 10': 'modelagem/cenarios/cenario10.md'
         - 'Cenario 11': 'modelagem/cenarios/cenario11.md'
         - 'Cenario 12': 'modelagem/cenarios/cenario12.md'
         - 'Cenario 13': 'modelagem/cenarios/cenario13.md'
         - 'Cenario 14': 'modelagem/cenarios/cenario14.md'
         - 'Cenario 15': 'modelagem/cenarios/cenario15.md'
         - 'Cenario 16': 'modelagem/cenarios/cenario16.md'
         - 'Cenario 17': 'modelagem/cenarios/cenario17.md'
         - 'Cenario 18': 'modelagem/cenarios/cenario18.md'
         - 'Cenario 19': 'modelagem/cenarios/cenario19.md'
         - 'Cenario 20': 'modelagem/cenarios/cenario20.md'
         - 'Cenario 21': 'modelagem/cenarios/cenario21.md'
         - 'Cenario 22': 'modelagem/cenarios/cenario22.md'
         - 'Cenario 23': 'modelagem/cenarios/cenario23.md'
         - 'Cenario 24': 'modelagem/cenarios/cenario24.md'
         - 'Cenario 25': 'modelagem/cenarios/cenario25.md'
         - 'Cenario 26': 'modelagem/cenarios/cenario26.md'
         - 'Cenario 27': 'modelagem/cenarios/cenario27.md'
         - 'Cenario 28': 'modelagem/cenarios/cenario28.md'
         - 'Cenario 29': 'modelagem/cenarios/cenario29.md'
         - 'Cenario 30': 'modelagem/cenarios/cenario30.md'
         - 'Cenario 31': 'modelagem/cenarios/cenario31.md'
         - 'Cenario 32': 'modelagem/cenarios/cenario32.md'
         - 'Cenario 33': 'modelagem/cenarios/cenario33.md'
theme:
    name: simplex
extra_css:
  - 'stylesheets/main.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.css'
extra_javascript:
  - 'stylesheets/fancybox-style/jquery.fancybox.js'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.js'
