site_name: Wiki
pages:
     - Home: index.md
     - Pré-Rastreabilidade:
         - 'About': 'pre-rastreabilidade/pre-rastreabilidade.md'
         - 'Rich Pictures': 'pre-rastreabilidade/richPictures/richPictures-VFinal.md'
         - 'Argumentações': 'pre-rastreabilidade/argumentacoes.md'
         - 'Referências': 'pre-rastreabilidade/referencias.md'
     - Pós-Rastreabilidade:
         - 'About': 'pos-rastreabilidade/pos-rastreabilidade.md'
         - 'Matrizes de Rastreabilidade': 'pos-rastreabilidade/matriz-rastreabilidade.md'
         - 'Backward-from': 'pos-rastreabilidade/backwardfrom.md'
         - 'Forward-from': 'pos-rastreabilidade/forwardfrom.md'
         - 'Referências': 'pos-rastreabilidade/referencias.md'
     - Elicitação:
         - 'About': 'elicitacao/elicitacao.md'
         - 'Técnicas Elicitação': 'elicitacao/tec_elicitacao.md'
         - 'Observação Participativa': 'elicitacao/observacao_participativa.md'
         - 'Questionário': 'elicitacao/questionario/questionario.md'
         - 'Introspecção': 'elicitacao/introspeccao.md'
         - 'Brainstorming': 'elicitacao/brainstorming.md'
         - 'Análise de Protocolo': 'elicitacao/analise_protocolo.md'
         - 'Analise de Discurso': 'elicitacao/analise_discurso.md'
         - 'Storytelling': 'elicitacao/storytelling.md'
         - 'Resultado Técnicas de Elicitação': 'elicitacao/resultado_final_TE.md'
         - 'Técnicas Priorização': 'elicitacao/tec_priorizacao.md'
         - 'MoSCoW': 'elicitacao/moscow.md'
         - 'First Things First': 'elicitacao/first_things_first.md'
         - 'Referências': 'elicitacao/referencias.md'
     - Modelagem:
         - 'About': 'modelagem/modelagem.md'
         - 'Léxicos': 'modelagem/lexicos.md'
         - 'Cenários': 'modelagem/cenarios.md'
         - 'Diagramas de Caso de Uso' : 'modelagem/DiagCasoDeUso.md'
         - 'Casos de Uso': 'modelagem/casosUso.md'
         - 'Especificação Suplementar': 'modelagem/EspSuplementar.md'
         - 'Historias de Usuário': 'modelagem/user_stories.md'
         - 'NFR': 'modelagem/NFRs/NFR-VFinal.md'
         - 'iStar': 'modelagem/iStar.md'
         - 'Referências': 'modelagem/referencias.md'
     - Análise:
         - 'About': 'analise/analise.md'
         - 'Verificação': 'analise/verificacao.md'


     - Extras:
         - 'Linha do Tempo': 'extras/linha-tempo.md'
         - 'Pautas de Reuniões': 'extras/reunioes.md'
         - 'Apresentações': 'extras/apresentacoes.md'
         - 'Pesquisa de Qualidade': 'extras/pesquisaqualidade.md'
     - Pages :
         - 'Versoes argumentacao': 'pre-rastreabilidade/argumentacoes/argumentacao-V1.md'
         - 'Versoes argumentacao FINAL': 'pre-rastreabilidade/argumentacoes/argumentacao-FINAL.md'
         - 'Cenario 01': 'modelagem/cenarios/cenario01.md'
         - 'Cenario 02': 'modelagem/cenarios/cenario02.md'
         - 'Cenario 03': 'modelagem/cenarios/cenario03.md'
         - 'Cenario 04': 'modelagem/cenarios/cenario04.md'
         - 'Cenario 05': 'modelagem/cenarios/cenario05.md'
         - 'Cenario 06': 'modelagem/cenarios/cenario06.md'
         - 'Cenario 07': 'modelagem/cenarios/cenario07.md'
         - 'Cenario 08': 'modelagem/cenarios/cenario08.md'
         - 'Cenario 09': 'modelagem/cenarios/cenario09.md'
         - 'Cenario 10': 'modelagem/cenarios/cenario10.md'
         - 'Cenario 11': 'modelagem/cenarios/cenario11.md'
         - 'Cenario 12': 'modelagem/cenarios/cenario12.md'
         - 'Cenario 13': 'modelagem/cenarios/cenario13.md'
         - 'Cenario 14': 'modelagem/cenarios/cenario14.md'
         - 'Cenario 15': 'modelagem/cenarios/cenario15.md'
         - 'Cenario 16': 'modelagem/cenarios/cenario16.md'
         - 'Cenario 17': 'modelagem/cenarios/cenario17.md'
         - 'Cenario 18': 'modelagem/cenarios/cenario18.md'
         - 'Cenario 19': 'modelagem/cenarios/cenario19.md'
         - 'Cenario 20': 'modelagem/cenarios/cenario20.md'
         - 'Cenario 21': 'modelagem/cenarios/cenario21.md'
         - 'Cenario 22': 'modelagem/cenarios/cenario22.md'
         - 'Cenario 23': 'modelagem/cenarios/cenario23.md'
         - 'Cenario 24': 'modelagem/cenarios/cenario24.md'
         - 'Cenario 25': 'modelagem/cenarios/cenario25.md'
         - 'Cenario 26': 'modelagem/cenarios/cenario26.md'
         - 'Cenario 27': 'modelagem/cenarios/cenario27.md'
         - 'Cenario 28': 'modelagem/cenarios/cenario28.md'
         - 'Cenario 29': 'modelagem/cenarios/cenario29.md'
         - 'Cenario 30': 'modelagem/cenarios/cenario30.md'
         - 'Cenario 31': 'modelagem/cenarios/cenario31.md'
         - 'Cenario 32': 'modelagem/cenarios/cenario32.md'
         - 'Cenario 33': 'modelagem/cenarios/cenario33.md'
         - 'Cenario 34': 'modelagem/cenarios/cenario34.md'
         - 'Cenario 35': 'modelagem/cenarios/cenario35.md'
         - 'Cenario 36': 'modelagem/cenarios/cenario36.md'
         - 'Cenario 37': 'modelagem/cenarios/cenario37.md'
         - 'Cenario 38': 'modelagem/cenarios/cenario38.md'
         - 'Cenario 39': 'modelagem/cenarios/cenario39.md'
         - 'UC 01': 'modelagem/casosUso/UC01.md'
         - 'UC 02': 'modelagem/casosUso/UC02.md'
         - 'UC 03': 'modelagem/casosUso/UC03.md'
         - 'UC 04': 'modelagem/casosUso/UC04.md'
         - 'UC 05': 'modelagem/casosUso/UC05.md'
         - 'UC 06': 'modelagem/casosUso/UC06.md'
         - 'UC 07': 'modelagem/casosUso/UC07.md'
         - 'UC 08': 'modelagem/casosUso/UC08.md'
         - 'UC 09': 'modelagem/casosUso/UC09.md'
         - 'UC 10': 'modelagem/casosUso/UC10.md'
         - 'UC 11': 'modelagem/casosUso/UC11.md'
         - 'UC 12': 'modelagem/casosUso/UC12.md'
         - 'UC 13': 'modelagem/casosUso/UC13.md'
         - 'UC 14': 'modelagem/casosUso/UC14.md'
         - 'UC 15': 'modelagem/casosUso/UC15.md'
         - 'UC 16': 'modelagem/casosUso/UC16.md'
         - 'UC 17': 'modelagem/casosUso/UC17.md'
         - 'UC 18': 'modelagem/casosUso/UC18.md'
         - 'UC 19': 'modelagem/casosUso/UC19.md'
         - 'UC 20': 'modelagem/casosUso/UC20.md'
         - 'UC 21': 'modelagem/casosUso/UC21.md'
         - 'UC 22': 'modelagem/casosUso/UC22.md'
         - 'UC 23': 'modelagem/casosUso/UC23.md'
         - 'UC 24': 'modelagem/casosUso/UC24.md'
         - 'UC 25': 'modelagem/casosUso/UC25.md'
         - 'UC 26': 'modelagem/casosUso/UC26.md'
         - 'UC 27': 'modelagem/casosUso/UC27.md'
         - 'Verificação da Argumentação': 'analise/verificacao/veargumentacao.md'
         - 'Verificação do Storytelling': 'analise/verificacao/vestorytelling.md'
         - 'Verificação da Análise de Protocolo': 'analise/verificacao/veprotocolo.md'
         - 'Verificação dos Casos de Uso': 'analise/verificacao/vecasodeuso.md'
         - 'Verificação das Histórias de Usuário': 'analise/verificacao/veuserstorie.md'
         - 'Verificação dos Cenários': 'analise/verificacao/vecenario.md'
         - 'Verificação dos Léxicos': 'analise/verificacao/velexico.md'
         - 'Verificação dos NFRs': 'analise/verificacao/venfr.md'
         - 'Verificação do iStar': 'analise/verificacao/veistar.md'
         - 'RP V1': 'pre-rastreabilidade/richPictures/richPictures-V1.md'
         - 'RP V1': 'pre-rastreabilidade/richPictures/richPictures-V2.md'
         - 'RP V1': 'pre-rastreabilidade/richPictures/richPictures-V3.md'
         - 'Diag de Caso de Uso V1': 'modelagem/DiagDeCasosUso/DiagCasodeUso-V1.md'
         - 'Diag de Caso de Uso FINAL': 'modelagem/DiagDeCasosUso/DiagCasodeUso-FINAL.md'
         - 'RP V2': 'pre-rastreabilidade/richPictures/richPictures-V2.md'
         - 'RP V3': 'pre-rastreabilidade/richPictures/richPictures-V3.md'
         - 'NFR V1': 'modelagem/NFRs/NFR-V1.md'


theme:
    name: simplex
extra_css:
  - 'stylesheets/main.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.css'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.css'
extra_javascript:
  - 'stylesheets/fancybox-style/jquery.fancybox.js'
  - 'stylesheets/fancybox-style/jquery.fancybox.min.js'
